### ISSUE TITLE
Unicorn migration guide

### ISSUE THREAD

**Issue by Earlopain** [Shopify/pitchfork#108]
Hey there,

I've been made aware of this project as an alternative to unicorn. It was pretty simple actually given that this started out as a fork but a few things had me thinking about what I need to do. I haven't rolled it out fully yet but cursory results seem pretty good. Would you be open to documentation for people coming from unicorn? I think it would be great to specifically call out actions that need to be taken. Things like:

* `working_directory` and `user` (among some others) being removed (favor someting like systemd instead)
* `USR2` being repurposed for reforking. I had reload configured in my unit file and my app isn't refork safe
* Linking to https://github.com/Shopify/pitchfork/issues/92 for `unicorn-worker-killer`
* renaming of `after_fork` to `after_worker_fork`

I will open a PR for this if you think it makes sense. There may be other things but this is what I stumbled across.

I also have a question: `before_fork` was removed early in this repos lifecycle and later added again. Do they behave the same?

**Comment by casperisfine** [comment]
> I will open a PR for this if you think it makes sense.

Sure.

> I also have a question: before_fork was removed early in this repos lifecycle and later added again. Do they behave the same?

Mostly yes.
