### ISSUE TITLE
Test failure against Rack 3.1

### ISSUE THREAD

**Issue by Earlopain** [Shopify/pitchfork#128]
Rack 3.1 added validation against `PATH_INFO`. That's fine, though there currently is one test that doesn't pass `Rack::Lint` because of that change: https://github.com/Shopify/pitchfork/blob/cd708bc111fc928a58dde2f83dce1eceb19030f2/test/unit/test_request.rb#L27-L35

Rack expects `PATH_INFO` to contain `*` (and enforces this through `Rack::Lint`), but pitchfork parses it into `REQUEST_URI` instead. That's my understanding at least.

https://github.com/rack/rack/blob/38b178e9ce3b30453cd5340a92093128bfb4fa36/lib/rack/lint.rb#L365-L388

````
   1) Error:
Pitchfork::RequestTest#test_options:
Rack::Lint::LintError: PATH_INFO must start with a '/' and must not include a fragment part starting with '#' (origin-form)
    vendor/bundle/ruby/3.3.0/gems/rack-3.1.0/lib/rack/lint.rb:385:in `check_environment'
    vendor/bundle/ruby/3.3.0/gems/rack-3.1.0/lib/rack/lint.rb:63:in `response'
    vendor/bundle/ruby/3.3.0/gems/rack-3.1.0/lib/rack/lint.rb:41:in `call'
    test/unit/test_request.rb:34:in `test_options'
````

**Comment by casperisfine** [comment]
IMO this is a bug on rack side. `OPTIONS * HTTP/1.1` is valid HTTP by the spec: https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.7

**Comment by Earlopain** [comment]
There is extra handling for `OPTION *` added in  https://github.com/rack/rack/pull/2114, perhaps it contains some useful info for you

**Comment by Earlopain** [comment]
Yeah, I'm looking at this as well right now. A bit unfortunate, Rack 3.0 (and probably 2 as well) still require `PATH_INFO` to start with `/`. It's easy enough to change there but then it would only comply with the latest version.

The parser probably needs to become aware of the rack version. Would you mind me creating a PR for this?
