### ISSUE TITLE
`require': cannot load such file -- pitchfork/pitchfork_http (LoadError)

### ISSUE THREAD

**Issue by jpcamara** [Shopify/pitchfork#18]
After bundle installing `pitchfork`, when I try to run it I get the following error:

```
bundle exec pitchfork

11: from /usr/local/cache/ruby/2.7.0/bin/pitchfork:23:in `<top (required)>'
10: from /usr/local/cache/ruby/2.7.0/bin/pitchfork:23:in `load'
9: from /usr/local/cache/ruby/2.7.0/gems/pitchfork-0.1.0/exe/pitchfork:3:in `<top (required)>'
8: from /usr/local/cache/ruby/2.7.0/gems/pitchfork-0.1.0/exe/pitchfork:3:in `require'
7: from /usr/local/cache/ruby/2.7.0/gems/pitchfork-0.1.0/lib/pitchfork/launcher.rb:9:in `<top (required)>'
6: from /usr/local/cache/ruby/2.7.0/gems/pitchfork-0.1.0/lib/pitchfork/launcher.rb:9:in `require'
5: from /usr/local/cache/ruby/2.7.0/gems/pitchfork-0.1.0/lib/pitchfork.rb:156:in `<top (required)>'
4: from /usr/local/cache/ruby/2.7.0/gems/pitchfork-0.1.0/lib/pitchfork.rb:156:in `each'
3: from /usr/local/cache/ruby/2.7.0/gems/pitchfork-0.1.0/lib/pitchfork.rb:157:in `block in <top (required)>'
2: from /usr/local/cache/ruby/2.7.0/gems/pitchfork-0.1.0/lib/pitchfork.rb:157:in `require_relative'
1: from /usr/local/cache/ruby/2.7.0/gems/pitchfork-0.1.0/lib/pitchfork/http_parser.rb:4:in `<top (required)>'
/usr/local/cache/ruby/2.7.0/gems/pitchfork-0.1.0/lib/pitchfork/http_parser.rb:4:in `require': cannot load such file -- pitchfork/pitchfork_http (LoadError)
```

Updating `http_parser.rb` to `require_relative` fixes the error, which then leads to the next error:
```rb
# lib/pitchfork/http_parser.rb

# require 'pitchfork/pitchfork_http'
require_relative '../pitchfork_http'
```

```
bundle exec pitchfork

/usr/local/cache/ruby/2.7.0/gems/pitchfork-0.1.0/lib/pitchfork/http_server.rb:2:in `require': cannot load such file -- pitchfork/pitchfork_http (LoadError)
```

Applying `require_relative` inside of `http_server.rb` fixes that error, and the server then starts.

```rb
# lib/pitchfork/http_server.rb

# require 'pitchfork/pitchfork_http'
require_relative '../pitchfork_http'
```

This seems to be because in the gem source, `pitchfork_http` is in `lib/pitchfork_http` (`pitchfork_http.so` on docker linux, `pitchfork_http.bundle` on mac os). But if I pull down the project and run `bundle exec rake compile`, `pitchfork_http` gets added directly to `lib/pitchfork/pitchfork_http`. The `require` works properly in this case, and the majority of the specs work as well.

Is this intentional and I have something misconfigured, or is there a problem with the published gem?

**Comment by casperisfine** [comment]
You're right, there's something weird with the 0.1.0 gem. The binary should be in `lib/pitchfork/` but somehow it ended up in `lib`.

Looking.

**Comment by jpcamara** [comment]
Works for me now 👌🏼 All good, it _is_ experimental after all 😉 Replaced unicorn with it for local dev and it's been working well so far
