### ISSUE TITLE
Sequel PG::ConnectionBad on refork.

### ISSUE THREAD

**Issue by skirushkin** [Shopify/pitchfork#76]
Hi, first I would like to thank you for amazing work!

I've rails application with `sequel-rails` gem. And sometimes (rare) on high traffic refork I'm getting this error:
```
PG::ConnectionBad: PQconsumeInput() server closed the connection unexpectedly (PG::ConnectionBad)
	This probably means the server terminated abnormally
	before or while processing the request.

  from sequel (5.74.0) lib/sequel/adapters/postgres.rb:171:in `exec'
  from sequel (5.74.0) lib/sequel/adapters/postgres.rb:171:in `block in execute_query'
  from sequel-rails (1.2.1) lib/sequel_rails/sequel/database/active_support_notification.rb:17:in `block in log_connection_yield'
  from activesupport (7.1.2) lib/active_support/notifications.rb:206:in `block in instrument'
  from activesupport (7.1.2) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
  from activesupport (7.1.2) lib/active_support/notifications.rb:206:in `instrument'
  from sequel-rails (1.2.1) lib/sequel_rails/sequel/database/active_support_notification.rb:11:in `log_connection_yield'
...
```

I've implemented disconnect on mold fork. Here my `config/pitchfork.rb`
```
# frozen_string_literal: true

worker_processes ENV.fetch("PITCHFORK_WORKERS", 1).to_i
listen 3000

refork_after [50, 100, 1000]

after_mold_fork do |_server, _mold|
  Sequel::DATABASES.each(&:disconnect)
end

after_worker_fork do |_server, _worker|
  SemanticLogger.reopen
end
```

**Comment by skirushkin** [comment]
> after_mold_fork is too late. You already forked off a worker at this point, so the new mold is disconnecting a connection that is shared with the original worker, so the server is closing even though the original worker is still using it.

Yes, I understand that. But when I just drop connections array in Sequel (e.g. `DB.pool.instance_variable_set(:@conn, [])`) the issue is still exist. So I checked your links and found that it depends on sequel fork safety https://github.com/jeremyevans/sequel/issues/1431. And seems Jeremy is not going to support `discard!` solution 🤷 .

But I decided to give it a try and created same AR socket reopen code in `after_mold_fork`.
```
after_mold_fork do |_server, _mold|
  DB.pool.instance_variable_get(:@conn).first.socket_io.reopen(IO::NULL)
  DB.pool.instance_variable_set(:@conn, [])
end
```
In this case issue is still reproducible. But I don't understand why. Also this solution doesn't work if I put it on `after_worker_fork`.

So next attempt to reproduce full AR behaviour. When I've created config/initializers/pitchfork.rb and removed `after_mold_fork` and `after_worker_fork` at all.
```
ActiveSupport::ForkTracker.after_fork do
  conn = DB.pool.instance_variable_get(:@conn)
  next if conn.blank?

  conn.first.socket_io.reopen(IO::NULL)
  DB.pool.instance_variable_set(:@conn, [])
end
```
This solution works like a charm 🤯 . 

I'll much appreciate if you can explain
1. Difference on socket reopen on `after_mold_fork` and `after_worker_fork` and `ActiveSupport::ForkTracker.after_fork`. Why only last point is right?
2. How `before_fork` hook on Pitchfork can help me? From my point I'll stuck in same problem. Or your mean that before_fork is called when mold parent is down?

**Comment by casperisfine** [comment]
That's why discarding connections in the child is a bit superior IMO, it doesn't disrupt the original connection in the parent.

**Comment by skirushkin** [comment]
> It will, but you are not supposed to have an in progress DB query. Reforking happens outside the request cycle.

It's strange cause original error I'm getting on reforking inside DB request in original worker.

**Comment by skirushkin** [comment]
Oh sorry for question, seems now I get it! Thank you so much for explanation! 

Can we ask you to implement `before_mold_fork` / `before_fork` hook? Seems it's really needed for Sequel 🙏
