### ISSUE TITLE
Weird behaviour reforking with Rails I18n translations

### ISSUE THREAD

**Issue by ollym** [Shopify/pitchfork#81]
We've been using pitchfork now in production for a week and on the whole it's been great.

One issue we've noticed though is randomly and in-frequently (happened 3 times in a week) a forked worker mysteriously loses all/some of the i18n keys and we get translations missing all over the place. We're not using anything fancy, just regular Rails 7 i18n. Our setup is 5-10 pods, 28 workers in each pod, handling ~50rps.

Before trying to investigate deeper, I wanted to check if anyone had experienced anything similar or anyone had any suggestions of where we should start looking.

Pitchfork config:

```ruby
# Sets the number of desired worker processes. Each worker process will serve exactly one client at a time.
worker_processes ENV.fetch('WEB_CONCURRENCY', 1).to_i

 # listen to port 3000 on all TCP interfaces
listen ENV.fetch('PORT', 3000).to_i, tcp_nopush: true

# nuke workers after 120 seconds instead of 60 seconds (the default)
timeout 120

# Enable this flag to have pitchfork test client connections by writing the
# beginning of the HTTP headers before calling the application.  This
# prevents calling the application for connections that have disconnected
# while queued.  This is only guaranteed to detect clients on the same
# host pitchfork runs on, and unlikely to detect disconnects even on a
# fast LAN.
check_client_connection false

# Sets a number of requests threshold for triggering an automatic refork.
# The limit is per-worker, for instance with refork_after [50] a refork is triggered once at least one worker processed 50 requests.
refork_after [500, 750, 1000, 1200, 1400, 1800, 2000, 2200, 2400, 2600, 2800, 3000, 3200, 3400, 3600, 3800, 4000, 4200, 4400, 4600, false]

# Called in the context of the mold after it has been spawned.
# Its usage is similar to a before_fork callback found on other servers but it is called once on promotion rather than before forking each worker.
# For most protocols connections can be closed after fork, but some stateful protocols require to close connections before fork.
# That is the case for instance of many SQL databases protocols.
# This is also the callback in which memory optimizations, such as heap compaction should be done.
after_mold_fork do |server, mold|
  ActiveRecord::Base.connection.disconnect! if defined?(ActiveRecord::Base)
end

# Called in the worker after forking.
# Generally used to close inherited connections or to restart backgrounds threads for libraries that don't do it automatically.
after_worker_fork do |server, worker|
  ActiveRecord::Base.establish_connection if defined?(ActiveRecord::Base)
  SemanticLogger.reopen if defined?(SemanticLogger)
end
```

**Comment by byroot** [comment]
> any suggestions of where we should start looking.

There really isn't anything in Ptichfork that would explain something like this.

I'd suggest detecting such case and exiting after dumping the heap with `ObjectSpace.dump_all` to try to better see what happened to the I18n data, in case it may give you some clues.

**Comment by byroot** [comment]
Another idea is to deep freeze `I18n` and it's internal data. So if it's some code responsible for clearing it, it should raise a FrozenError.

**Comment by casperisfine** [comment]
I'm gonna close as at this stage there is not much evidence it is a Pitchfork bug, so it's not actionable for me, but please keep this issue updated, if it is indeed caused by Pitchfork I'll gladly make the necessary changes.
